# Generated by Django 3.1.7 on 2021-03-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210318_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Laptop'), ('lni-leaf', 'Folha'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=17, verbose_name='Icone'),
        ),
    ]
